baseURL = "//lv-starvsroynd/"
languageCode = "fo"
title = "Landsverk Starvsroynd"

[params]
  description = "Finn út av, hvussu tú kanst brúka tínar førleikar hjá Landsverk"
  contactEmail = "lv@lv.fo"

[build]
  [build.buildStats]
    enable = true
