baseURL = "https://bartal-io.github.io/lv-starvsroynd/"
languageCode = "fo"
title = "Landsverk Starvsroynd"
relativeURLs = true

[params]
  description = "Finn út av, hvussu tú kanst brúka tínar førleikar hjá Landsverk"
  contactEmail = "lv@lv.fo"

[build]
  [build.buildStats]
    enable = true
